- hosts: all
  become: true
  gather_facts: true
  pre_tasks:
  - name: install prerequisites
    ansible.builtin.apt:
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  tasks:
  - name: add apt-key
    ansible.builtin.apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker repo
    ansible.builtin.apt_repository:
      repo: "deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"

  - name: install docker
    ansible.builtin.apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      update_cache: yes

  - name: add userpermissions
    ansible.builtin.user:
      name: vagrant
      groups: docker
      append: yes
